### ISSUE TITLE
Why run the fio command with `--bs=256k` instead of `--bs=2300`?

### ISSUE THREAD

**Issue by microyahoo** [ahrtr/etcd-issues#6]
Thanks for your sharing with article [how to debug performance issue](https://github.com/ahrtr/etcd-issues/blob/master/docs/troubleshooting/how_to_debug_performance_issue.md). 
In the section of fio, you mentioned it's recommended to set `--bs=2300`, why do you set `--bs=256k` in your fio example? Thanks in advance.
> See an example below, note based on [this link](https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fast-enough-for-etcd), it's recommended to set --bs=2300 because almost all WAL write size are in the range 2200-2400.

In addtion, I found aother article also mentioned, but it set --bs to 2300.
https://gist.github.com/patrick0057/16b1e9510095b2675ed74540556b6712#testing-etcd-performance

**Comment by ahrtr** [comment]
> In the section of fio, you mentioned it's recommended to set `--bs=2300`, why do you set `--bs=256k` in your fio example?

The example is just to show how to use the tool `fio`. The command and output was copied directly from one of my previous test results executed about 2 years ago.

**Comment by microyahoo** [comment]
Got it, thanks for your quick response.
